system('npm init -y')
system('npm install --save webpack react react-spinners moment lodash react-stars react-dom react-stars react-router-dom react-redux redux redux-logger redux-thunk babel-core babel-loader babel-preset-react babel-preset-env')
system('(export PKG=react-dates; npm info "$PKG" peerDependencies --json | command sed \'s/[\{\},]//g ; s/: /@/g; s/ *//g\' | xargs npm install --save "$PKG" )')
system('bundle install')
system('rails db:create')
system('rails db:migrate')
